apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confluent

resources:
  - namespace.yaml
  - connect.yaml
  - control-center.yaml
  - kraft-controller.yaml
  - kafka-broker.yaml
  - schema-registry.yaml

commonLabels:
  app.kubernetes.io/part-of: confluent-platform
