apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- argocd.yaml ## TODO needs more investigation for seamless, automated self-management
- argocd-config.yaml
- argocd-ingress.yaml
- cert-manager.yaml
- cert-manager-resources.yaml
- kube-prometheus-stack-crds.yaml
- kube-prometheus-stack.yaml
- longhorn.yaml
- traefik.yaml