apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "105"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://packages.confluent.io/helm
    chart: confluent-for-kubernetes
    targetRevision: 0.921.32
    helm:
      valueFiles:
        - $values/workloads/confluent-operator/base/values.yaml
        - $values/workloads/confluent-operator/overlays/portcullis/values.yaml
  sources:
    - repoURL: https://packages.confluent.io/helm
      chart: confluent-for-kubernetes
      targetRevision: 0.921.32
      helm:
        valueFiles:
          - $values/workloads/confluent-operator/base/values.yaml
          - $values/workloads/confluent-operator/overlays/portcullis/values.yaml
    - repoURL: https://github.com/osowski/homelab-argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
