apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: confluent

bases:
  - ../../base

# Optional: Add storage class patches here if needed
# patchesStrategicMerge:
#   - storage-patch.yaml
