# ArgoCD Overlay Configuration for Portcullis Cluster

global:
  domain: argocd.portcullis.osow.ski

server:
  config:
    url: https://argocd.portcullis.osow.ski
    
    resource.customizations.health.networking.k8s.io_Ingress: |
      hs = {}
      hs.status = "Healthy"
      return hs

  ingress:
    enabled: true
    hosts:
      - argocd.portcullis.osow.ski
