deployment:
  kind: DaemonSet
service:
  type: LoadBalancer
#nodeSelector:
#  ingress-ready: 'true'
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule

